// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function KillProcesses(arg1) {
  return window['go']['main']['App']['KillProcesses'](arg1);
}

export function SearchAllPorts() {
  return window['go']['main']['App']['SearchAllPorts']();
}

export function SearchPort(arg1) {
  return window['go']['main']['App']['SearchPort'](arg1);
}
