// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function KillProcess(arg1:string):Promise<main.KillResult>;

export function KillProcesses(arg1:Array<string>):Promise<Array<main.KillResult>>;

export function SearchAllPorts():Promise<Array<main.ProcessInfo>>;

export function SearchPort(arg1:string):Promise<Array<main.ProcessInfo>>;

export function SearchPorts(arg1:string):Promise<Array<main.ProcessInfo>>;
